<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Theme_Sniffer\\Admin_Menus\\Sniff_Page' => 'get5d7cfc2a785cc220617420',
  'Theme_Sniffer\\Api\\Template_Tags_Request' => 'get5d7cfc2a79dc9660528897',
  'Theme_Sniffer\\Callback\\Run_Sniffer_Callback' => 'get5d7cfc2a79dd2927786611',
  'Theme_Sniffer\\Enqueue\\Enqueue_Resources' => 'get5d7cfc2a79dd5616357854',
  'Theme_Sniffer\\i18n\\Internationalization' => 'get5d7cfc2a79dd8669402624',
);

    protected function get5d7cfc2a785cc220617420()
    {
        $object = new Theme_Sniffer\Admin_Menus\Sniff_Page();
        return $object;
    }

    protected function get5d7cfc2a79dc9660528897()
    {
        $object = new Theme_Sniffer\Api\Template_Tags_Request();
        return $object;
    }

    protected function get5d7cfc2a79dd2927786611()
    {
        $object = new Theme_Sniffer\Callback\Run_Sniffer_Callback();
        return $object;
    }

    protected function get5d7cfc2a79dd5616357854()
    {
        $object = new Theme_Sniffer\Enqueue\Enqueue_Resources();
        return $object;
    }

    protected function get5d7cfc2a79dd8669402624()
    {
        $object = new Theme_Sniffer\i18n\Internationalization();
        return $object;
    }

}
